# Generated by Django 3.2.8 on 2021-10-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['id'], 'verbose_name': 'Contactos', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='contacto',
        ),
    ]
