# Generated by Django 3.2.8 on 2021-10-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['id'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['id'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelTable(
            name='estado',
            table='estado',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
    ]
