# Generated by Django 3.2.8 on 2021-10-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidad',
            options={'ordering': ['id'], 'verbose_name': 'Oportunidad', 'verbose_name_plural': 'Oportunidades'},
        ),
        migrations.AlterModelTable(
            name='oportunidad',
            table='Oportunidad',
        ),
    ]
