# Generated by Django 3.2.8 on 2021-10-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=1)),
                ('nom_empresa', models.CharField(max_length=300)),
                ('nom_comercial', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.IntegerField(default=1)),
                ('correo', models.EmailField(max_length=150)),
                ('web', models.URLField()),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
