# Generated by Django 3.2.8 on 2021-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['id'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='image',
            field=models.ImageField(blank=True, upload_to='empresa/'),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
    ]
