# Generated by Django 3.2.8 on 2021-10-11 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0005_auto_20211010_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usu_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
